Decorate_and_delight/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('accounts/', include('accounts.urls')),
                  path('store/', include('store.urls')),
                  path('cart/', include('cart.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('logout/', logout_view, name='logout'),
    path('edit-profile/', edit_profile_view, name='edit_profile'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'),
         name='change_password'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),

]

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('add-to-cart/<int:product_id>/', add_cart_view, name='add_cart'),

    path('', cart_view, name='cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart_view, name='remove_cart'),
    # path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item_view, name='remove_cart_item'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item_view, name='remove_cart_item'),

    path('checkout/', checkout_view, name='checkout'),
    # path('add_cart/<int:product_id>/', add_cart_view, name='add_cart'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)


class CustomUser(AbstractUser):
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

store/models.py
from django.db import models
from accounts.models import CustomUser
import datetime
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='uploads/category_images/', blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='uploads/category_images/', blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.category.name} - {self.name}"


class Products(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default="")
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True, blank=True, default="")
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    description = models.CharField(max_length=350, default='', blank=True, null=True)
    image = models.ImageField(upload_to='uploads/product/')
    is_stock = models.BooleanField(default=True)
    stock_amount = models.IntegerField(default=1)
    ratings = models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])

    created_date = models.DateTimeField(default=timezone.now, editable=False)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# class ReviewRatings(models.Model):


class Order(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length=100, default='', blank=True)
    phone = models.CharField(max_length=15, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product} - {self.user}"

accounts/forms.py
from django import forms
from accounts.models import CustomUser
from django.forms.widgets import ClearableFileInput

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    # Override the username field to customize help text
    username = forms.CharField(
        max_length=150,
        help_text='',  # Set an empty string to hide the help text
        # widget=forms.TextInput(attrs={'placeholder': 'Username'}),  # Optional: Add a placeholder to the input field
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, required=False)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'phone_number', 'address', 'password',
                  'confirm_password', 'profile_image', 'gender']

    # def clean_username(self):
    #     username = self.cleaned_data.get('username')
    #     if CustomUser.objects.filter(username=username).exists():
    #         raise forms.ValidationError('This username is already taken.')
    #     return username

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'address', 'profile_image', 'gender', 'phone_number']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': "block mb-6 px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 "
                                                          "bg-transparent rounded-lg border-1 border-gray-300 "
                                                          "appearance-none dark:text-black dark:border-gray-600 "
                                                          "dark:focus:border-blue-500 focus:outline-none focus:ring-0 "
                                                          "focus:border-blue-600 peer"}),

            'last_name': forms.TextInput(attrs={'class': "block px-2.5 mb-6 pb-2.5 pt-4 w-full text-sm text-gray-900 "
                                                         "bg-transparent rounded-lg border-1 border-gray-300 "
                                                         "appearance-none dark:text-black dark:border-gray-600 "
                                                         "dark:focus:border-blue-500 focus:outline-none focus:ring-0 "
                                                         "focus:border-blue-600 peer"}),

            'phone_number': forms.TextInput(
                attrs={'class': "block px-2.5 mb-6 pb-2.5 pt-4 w-full text-sm text-gray-900 "
                                "bg-transparent rounded-lg border-1 border-gray-300 "
                                "appearance-none dark:text-black dark:border-gray-600 "
                                "dark:focus:border-blue-500 focus:outline-none focus:ring-0"
                                "focus:border-blue-600 peer"}),

            'address': forms.TextInput(attrs={'class': "block px-2.5 mb-6 pb-2.5 pt-4 w-full text-sm text-gray-900 "
                                                       "bg-transparent rounded-lg border-1 border-gray-300 "
                                                       "appearance-none dark:text-black dark:border-gray-600 "
                                                       "dark:focus:border-blue-500 focus:outline-none focus:ring-0 "
                                                       "focus:border-blue-600 peer"}),

            'gender': forms.Select(attrs={'class': 'bg-gray-50 border my-5 border-gray-300 text-gray-900 text-sm '
                                                   'rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full '
                                                   'p-2.5 dark:bg-white dark:border-gray-600 '
                                                   'dark:placeholder-gray-400 dark:text-black '
                                                   'dark:focus:ring-blue-500 dark:focus:border-blue-500'}),

            'profile_image': ClearableFileInput(attrs={
                'class': 'block w-full text-lg text-gray-900 border border-gray-300 rounded-lg cursor-pointer '
                         'bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-white '
                         'dark:border-gray-600 dark:placeholder-gray-400',
                'accept': 'image/*',  # Allow only image files
            })
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegistrationForm
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth import authenticate, login, logout
from .forms import EditProfileForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from cart.models import Cart, CartItem
from cart.views import _cart_id

CustomUser = get_user_model()


# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')

            # Check if username or email is already taken
            if CustomUser.objects.filter(username=username).exists():
                messages.error(request, 'This username is already taken.')
            elif CustomUser.objects.filter(email=email).exists():
                messages.error(request, 'This email is already associated with an account.')
            else:
                form.save()
                # Redirect to a success page or login page
                return redirect('login')  # Assuming you have a URL pattern named 'login'
        else:
            # If form is not valid, show form-level error messages
            error_message = form.errors.get('__all__')
            if error_message:
                messages.error(request, error_message)
            if 'username' in form.errors:
                messages.error(request, 'This username is already taken.')
            if 'email' in form.errors:
                messages.error(request, 'This email is already associated with an account.')
    else:
        form = RegistrationForm()

    return render(request, 'signup.html', {'form': form})


def login_view(request):
    form = LoginForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                # For redirect to previous page after login
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('home')
            else:
                form.add_error('password', 'Invalid email or password')  # Add custom form-level error
                # You can also use messages framework to display the error message
                messages.add_message(request, messages.ERROR, 'Invalid email or password')

    context = {
        'form': form
    }
    return render(request, 'login.html', context)

# Existing login view logic
# def login_view(request):
#     form = LoginForm(request.POST or None)
#
#     if request.method == 'POST':
#         if form.is_valid():
#             email = form.cleaned_data.get('email')
#             password = form.cleaned_data.get('password')
#             user = authenticate(request, username=email, password=password)
#
#             if user is not None:
#                 login(request, user)
#
#                 # Merge guest cart with user's cart upon successful login
#                 if 'cart_id' in request.session:
#                     guest_cart = Cart.objects.get(cart_id=request.session['cart_id'])
#                     guest_cart_items = CartItem.objects.filter(cart=guest_cart)
#
#                     # Check if the user already has a cart
#                     if user.cart:
#                         user_cart_items = CartItem.objects.filter(cart=user.cart)
#                         for item in guest_cart_items:
#                             # Check if the item is already present in the user's cart
#                             if user_cart_items.filter(product=item.product).exists():
#                                 existing_item = user_cart_items.get(product=item.product)
#                                 existing_item.quantity += item.quantity
#                                 existing_item.save()
#                             else:
#                                 item.cart = user.cart
#                                 item.save()
#                     else:
#                         for item in guest_cart_items:
#                             item.cart = user.cart
#                             item.save()
#
#                     # Clear guest cart or its session
#                     guest_cart.delete()
#                     del request.session['cart_id']
#
#                 return redirect('home')
#             else:
#                 form.add_error('password', 'Invalid email or password')
#                 messages.add_message(request, messages.ERROR, 'Invalid email or password')
#
#     context = {
#         'form': form
#     }
#     return render(request, 'login.html', context)


def logout_view(request):
    logout(request)
    return redirect('login')


def dashboard_view(request):
    return render(request, 'dashboard.html')


@login_required
def edit_profile_view(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save(commit=False)
            # Extract the cleaned data from the form
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            address = form.cleaned_data['address']
            profile_image = form.cleaned_data['profile_image']
            gender = form.cleaned_data['gender']

            # Retrieve the current user instance
            user = request.user

            # Update fields only if they are provided in the form
            if first_name:
                user.first_name = first_name
            if last_name:
                user.last_name = last_name
            if phone_number:
                user.phone_number = phone_number
            if address:
                user.address = address
            if profile_image:
                user.profile_image = profile_image
            if gender:
                user.gender = gender

            # Save the updated user instance
            user.save()

            messages.success(request, 'Your profile has been updated successfully.')
            return redirect('home')  # Assuming you have a URL pattern named 'profile'
        else:
            messages.error(request, 'Error updating profile. Please check the form data.')
    else:
        form = EditProfileForm(instance=request.user)

    return render(request, 'settings.html', {'form': form})


class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'change_password.html'
    success_url = '/change-password/done/'  # Redirect to this URL after password change

accounts/templates/change_password.html
{% extends 'base.html' %}

{% block title %}
        Change Password
{% endblock title %}

{% block content %}

<h1 class="mb-6 text-3xl text-green-800 text-center">Change Password</h1>

<div class="container mx-auto w-2/4">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">Change Password</button>
  </form>
</div>

{% endblock content %}

accounts/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
        Dashboard
{% endblock title %}| D&D


{% block content %}

This is from Dashboard
{% endblock content %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}
        Register
{% endblock title %}| D&D


{% block content %}

This is from Signup


<h1 class="mb-6 text-3xl text-green-800 text-center">Sign-Up</h1>

<!-- <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Register</button>
</form> -->
<!-- {% if username_taken %}
<div class="alert alert-danger mb-4">
  This username is already taken. Change a few things up and try submitting again.
</div>
{% endif %} -->
<div class="container mx-auto w-2/4">
  <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Render your form fields here -->
    <!-- <label for="id_username">Username:</label>
    <input type="text" name="username" id="id_username" required> -->
    <div class="relative">
      <input type="text" name="username" id="id_username" required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label for="id_username"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Username</label>
    </div>

    <br>

    <!-- <label for="id_email">Email:</label>
    <input type="email" name="email" id="id_email" required> -->
    <div class="relative">
      <input type="email" name="email" id="id_email" required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label for="id_email"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Email</label>
    </div>
    <br>

    <!-- <label for="id_first_name">First Name:</label>
    <input type="text" name="first_name" id="id_first_name" required> -->
    <div class="relative">
      <input type="text" name="first_name" id="id_first_name" required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label for="id_first_name"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">First Name</label>
    </div>

    <br>

    <!-- <label for="id_last_name">Last Name:</label>
    <input type="text" name="last_name" id="id_last_name" required> -->

    <div class="relative">
      <input type="text" name="last_name" id="id_last_name" required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label for="id_last_name"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Last Name</label>
    </div>
    <br>

    <!-- <label for="id_phone">Phone Number:</label>
    <input type="text" name="phone_number" id="id_phone" required> -->
    <div class="relative">
      <input type="text" name="phone_number" id="id_phone"  required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label for="id_phone"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Phone Number</label>
    </div>
    <br>

    <!-- <label for="id_address">Address:</label>
    <input type="text" name="address" id="id_address" required> -->

    <div class="relative">
      <input type="text" name="address" id="id_address"   required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label  for="id_address"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Address</label>
    </div>
    <br>

<!--    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-black" for="large_size">Profile picture</label>-->
<input class="block w-full text-lg text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-white dark:border-gray-600 dark:placeholder-gray-400" id="large_size" type="file" name="profile_image">

    <br>
    <div class="relative">
    <select name="gender" id="id_gender"
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer">
        <option value="" selected>Select Gender</option>
        {% for value, label in form.fields.gender.choices %}
            <option value="{{ value }}">{{ label }}</option>
        {% endfor %}
    </select>
    <label for="id_gender"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Gender</label>
</div>
<br>
    <!-- <label for="id_password">Password:</label>
    <input type="password" name="password" id="id_password" required> -->

    <div class="relative">
      <input type="password" name="password" id="id_password"   required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label   for="id_password"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Password</label>
    </div>
    <br>

    <!-- <label for="id_confirm_password">Confirm Password:</label>
    <input type="password" name="confirm_password" id="id_confirm_password" required> -->
    <div class="relative">
      <input  type="password" name="confirm_password" id="id_confirm_password"   required
        class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
        placeholder=" " />
      <label   for="id_confirm_password"
        class="absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white  px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Confirm Password</label>
    </div>
    <br>

    <!-- Add other form fields as needed -->

    <!-- <button type="submit">Register</button> -->
    <button type="submit" class="focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">Register</button>
  </form>
    Already have an account? <a href="{% url 'login' %}" class="text-blue-600">Login.</a>
  {% for message in messages %}

  <div class="p-4 my-6 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
      <span class="font-medium">{{ message }}</span>
  </div>

  {% endfor %}

</div>

<script>
  // Automatically hide error messages after 5 seconds
  const errorMessages = document.querySelectorAll('.text-red-800');
  errorMessages.forEach(message => {
    setTimeout(() => {
      message.classList.add('invisible');
    }, 5000); // 5000 milliseconds (5 seconds)
  });
</script>

{% endblock content %}